# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('guildID', models.AutoField(primary_key=True, serialize=False)),
                ('guildName', models.CharField(max_length=30, verbose_name='Guild Name')),
                ('guildLevel', models.IntegerField(default=1)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.Character')),
            ],
        ),
    ]
